// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB63F6Sd8R9vuBnkgEM6osAqj3HZvENZrU',
    appId: '1:365028872680:web:e66d9fc1fc61ab846f145d',
    messagingSenderId: '365028872680',
    projectId: 'coupon-52cb0',
    authDomain: 'coupon-52cb0.firebaseapp.com',
    storageBucket: 'coupon-52cb0.appspot.com',
    measurementId: 'G-RKLS21R4RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq_qgrtdqD215Cof02VMdmhxe1GV2Wg-0',
    appId: '1:365028872680:android:dec5c425bf43fa856f145d',
    messagingSenderId: '365028872680',
    projectId: 'coupon-52cb0',
    storageBucket: 'coupon-52cb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlMigYv75uzzPgwBBR0hvOT1yxrgetmp0',
    appId: '1:365028872680:ios:e13dc1e0075993cf6f145d',
    messagingSenderId: '365028872680',
    projectId: 'coupon-52cb0',
    storageBucket: 'coupon-52cb0.appspot.com',
    iosBundleId: 'com.Homdapp.coppon3pp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlMigYv75uzzPgwBBR0hvOT1yxrgetmp0',
    appId: '1:365028872680:ios:e13dc1e0075993cf6f145d',
    messagingSenderId: '365028872680',
    projectId: 'coupon-52cb0',
    storageBucket: 'coupon-52cb0.appspot.com',
    iosBundleId: 'com.Homdapp.coppon3pp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB63F6Sd8R9vuBnkgEM6osAqj3HZvENZrU',
    appId: '1:365028872680:web:b6515dc3e0c53d7b6f145d',
    messagingSenderId: '365028872680',
    projectId: 'coupon-52cb0',
    authDomain: 'coupon-52cb0.firebaseapp.com',
    storageBucket: 'coupon-52cb0.appspot.com',
    measurementId: 'G-KG7D91QMC2',
  );
}
